---
- name: Install dotfiles
  git: repo=git@github.com:gzhelyaz/dotfiles.git dest=~/.dotfiles

- name: Symlink dotfiles
  file: src=~/.dotfiles/{{ item }}
        dest=~/.{{ item }}
        state=link
        force=yes
  with_items:
    - bashrc
    - gitconfig
    - inputrc
    - tmux.conf
    - vimrc
    - zprofile
    - zshrc

